//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtate.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom action does not configured..
        /// </summary>
        internal static string Assertion_CustomActionDoesNotConfigured {
            get {
                return ResourceManager.GetString("Assertion_CustomActionDoesNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects structure mismatch..
        /// </summary>
        internal static string Assertion_ObjectsStructureMismatch {
            get {
                return ResourceManager.GetString("Assertion_ObjectsStructureMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: [{0}]. Name: [{1}]. SessionId: [{2}]. SourceEntityId: [{3}]. Exception: {4}.
        /// </summary>
        internal static string DefaultLogger_LogError {
            get {
                return ResourceManager.GetString("DefaultLogger_LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: [{0}]. SessionId: [{1}]. Message: &quot;{2}&quot;. Arguments: {3} Exception: {4}.
        /// </summary>
        internal static string DefaultLogger_LogInfo {
            get {
                return ResourceManager.GetString("DefaultLogger_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel event. SendId: [{0}]..
        /// </summary>
        internal static string DefaultLogger_TraceCancelEvent {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceCancelEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel invoke. InvokeId: [{0}]..
        /// </summary>
        internal static string DefaultLogger_TraceCancelInvoke {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceCancelInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered to state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceEnteredState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceEnteredState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering to state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceEnteringState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceEnteringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exited from state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceExitedState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceExitedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting from state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceExitingState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceExitingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreter state has changed to [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceInterpreterState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceInterpreterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed {0} transition to: [{1}]. Event: [{2}]. SessionId: [{3}]..
        /// </summary>
        internal static string DefaultLogger_TracePerformedTransition {
            get {
                return ResourceManager.GetString("DefaultLogger_TracePerformedTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing {0} transition to: [{1}]. Event: [{2}]. SessionId: [{3}]..
        /// </summary>
        internal static string DefaultLogger_TracePerformingTransition {
            get {
                return ResourceManager.GetString("DefaultLogger_TracePerformingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} event [{1}]. SendId: [{2}]. InvokeId: [{3}]. Data: [{4}]. OriginType: [{5}]. Origin: [{6}]. SessionId: [{7}]..
        /// </summary>
        internal static string DefaultLogger_TraceProcessingEvent {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceProcessingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send event: [{0}]. SendId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceSendEvent {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceSendEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start invoke. InvokeId: [{0}]..
        /// </summary>
        internal static string DefaultLogger_TraceStartInvoke {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceStartInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array property required for ForEach element.
        /// </summary>
        internal static string ErrorMessage_ArrayPropertyRequiredForForEach {
            get {
                return ResourceManager.GetString("ErrorMessage_ArrayPropertyRequiredForForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression or Inline content should be specified in Assign element..
        /// </summary>
        internal static string ErrorMessage_AssignItemContentAndExpressionMissed {
            get {
                return ResourceManager.GetString("ErrorMessage_AssignItemContentAndExpressionMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Inline content can&apos;t be used at the same time in Assign element..
        /// </summary>
        internal static string ErrorMessage_AssignItemContentAndExpressionSpecified {
            get {
                return ResourceManager.GetString("ErrorMessage_AssignItemContentAndExpressionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location missed in Assign element..
        /// </summary>
        internal static string ErrorMessage_AssignItemLocationMissed {
            get {
                return ResourceManager.GetString("ErrorMessage_AssignItemLocationMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one attribute url or urlExpr must be specified.
        /// </summary>
        internal static string ErrorMessage_AtLeastOneUrlMustBeSpecified {
            get {
                return ResourceManager.GetString("ErrorMessage_AtLeastOneUrlMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;attr&apos; attribute should not be empty..
        /// </summary>
        internal static string ErrorMessage_AttrAttributeShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorMessage_AttrAttributeShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendId or SendIdExpression should be specified in Cancel element..
        /// </summary>
        internal static string ErrorMessage_CancelItemSendIdAndExpressionMissed {
            get {
                return ResourceManager.GetString("ErrorMessage_CancelItemSendIdAndExpressionMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendId and SendIdExpression can&apos;t be used at the same time in Cancel element..
        /// </summary>
        internal static string ErrorMessage_CancelItemSendIdAndExpressionSpecified {
            get {
                return ResourceManager.GetString("ErrorMessage_CancelItemSendIdAndExpressionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition expression can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_ConditionExpressionCantBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionExpressionCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition property required for ElseIf element..
        /// </summary>
        internal static string ErrorMessage_ConditionRequiredForElseIf {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionRequiredForElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition property required for ForEach element..
        /// </summary>
        internal static string ErrorMessage_ConditionRequiredForForEach {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionRequiredForForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition property required for If element..
        /// </summary>
        internal static string ErrorMessage_ConditionRequiredForIf {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionRequiredForIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content value can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_ContentValueCantBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ContentValueCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom action executor can&apos;t be found..
        /// </summary>
        internal static string ErrorMessage_CustomActionExecutorCantBeFound {
            get {
                return ResourceManager.GetString("ErrorMessage_CustomActionExecutorCantBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModel not supported in NULL data model..
        /// </summary>
        internal static string ErrorMessage_DataModelNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMessage_DataModelNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModel not supported in &apos;runtime&apos; data model..
        /// </summary>
        internal static string ErrorMessage_DataModelNotSupportedInRuntime {
            get {
                return ResourceManager.GetString("ErrorMessage_DataModelNotSupportedInRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected unknown element &lt;{0}&gt;..
        /// </summary>
        internal static string ErrorMessage_DetectedUnknownElement {
            get {
                return ResourceManager.GetString("ErrorMessage_DetectedUnknownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoneData not supported in NULL data model..
        /// </summary>
        internal static string ErrorMessage_DoneDataNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMessage_DoneDataNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;else&gt; can be used only once..
        /// </summary>
        internal static string ErrorMessage_ElseCanBeUsedOnlyOnce {
            get {
                return ResourceManager.GetString("ErrorMessage_ElseCanBeUsedOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;elseif&gt; can not follow &lt;else&gt;..
        /// </summary>
        internal static string ErrorMessage_ElseifCannotFollowElse {
            get {
                return ResourceManager.GetString("ErrorMessage_ElseifCannotFollowElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on creation CustomAction executor..
        /// </summary>
        internal static string ErrorMessage_ErrorOnCreationCustomActionExecutor {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorOnCreationCustomActionExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event, EventExpression and Content can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_EvenExpressionContentInSend {
            get {
                return ResourceManager.GetString("ErrorMessage_EvenExpressionContentInSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event and EventExpression can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_EventExpressionInSend {
            get {
                return ResourceManager.GetString("ErrorMessage_EventExpressionInSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event property required for Raise element..
        /// </summary>
        internal static string ErrorMessage_EventRequiredForRaise {
            get {
                return ResourceManager.GetString("ErrorMessage_EventRequiredForRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected element &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ErrorMessage_ExpectedElementNotFound {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpectedElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression or Body should be specified in Content element..
        /// </summary>
        internal static string ErrorMessage_ExpressionAndBodyMissedInContent {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionAndBodyMissedInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Body can&apos;t be used at the same time in Content element..
        /// </summary>
        internal static string ErrorMessage_ExpressionAndBodySpecifiedInContent {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionAndBodySpecifiedInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Location can&apos;t be used at the same time in Param element..
        /// </summary>
        internal static string ErrorMessage_ExpressionLocationInParam {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionLocationInParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Source and Inline content can&apos;t be used at the same time in Data element..
        /// </summary>
        internal static string ErrorMessage_ExpressionSourceInData {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionSourceInData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure on attribute processing..
        /// </summary>
        internal static string ErrorMessage_FailureAttributeProcessing {
            get {
                return ResourceManager.GetString("ErrorMessage_FailureAttributeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure on raw content processing..
        /// </summary>
        internal static string ErrorMessage_FailureContentProcessing {
            get {
                return ResourceManager.GetString("ErrorMessage_FailureContentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure on element processing..
        /// </summary>
        internal static string ErrorMessage_FailureElementProcessing {
            get {
                return ResourceManager.GetString("ErrorMessage_FailureElementProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForEach not supported in NULL data model..
        /// </summary>
        internal static string ErrorMessage_ForEachNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ForEachNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found duplicate attribute &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMessage_FoundDuplicateAttribute {
            get {
                return ResourceManager.GetString("ErrorMessage_FoundDuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id and IdLocation can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_IdAndIdLocationCantBeUsedAtTheSameTimeInInvokeElement {
            get {
                return ResourceManager.GetString("ErrorMessage_IdAndIdLocationCantBeUsedAtTheSameTimeInInvokeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id and IdLocation can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_IdAndIdLocationCantBeUsedAtTheSameTimeInSendElement {
            get {
                return ResourceManager.GetString("ErrorMessage_IdAndIdLocationCantBeUsedAtTheSameTimeInSendElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id property required in Data element..
        /// </summary>
        internal static string ErrorMessage_IdPropertyRequiredInDataElement {
            get {
                return ResourceManager.GetString("ErrorMessage_IdPropertyRequiredInDataElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect condition expression..
        /// </summary>
        internal static string ErrorMessage_IncorrectConditionExpression {
            get {
                return ResourceManager.GetString("ErrorMessage_IncorrectConditionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format of condition expression for NULL data model..
        /// </summary>
        internal static string ErrorMessage_IncorrectConditionExpressionForNull {
            get {
                return ResourceManager.GetString("ErrorMessage_IncorrectConditionExpressionForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial attribute and Initial state can&apos;t be used at the same time in State element..
        /// </summary>
        internal static string ErrorMessage_InitialAttributeAndInitialStateCantBeUsedAtTheSameTimeInStateElement {
            get {
                return ResourceManager.GetString("ErrorMessage_InitialAttributeAndInitialStateCantBeUsedAtTheSameTimeInStateElement" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state/property can be used only in complex (compound) states..
        /// </summary>
        internal static string ErrorMessage_InitialStatePropertyCanBeUsedOnlyInComplexStates {
            get {
                return ResourceManager.GetString("ErrorMessage_InitialStatePropertyCanBeUsedOnlyInComplexStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state/property cannot be used without any states..
        /// </summary>
        internal static string ErrorMessage_InitialStatePropertyCannotBeUsedWithoutAnyStates {
            get {
                return ResourceManager.GetString("ErrorMessage_InitialStatePropertyCannotBeUsedWithoutAnyStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BindingType value in StateMachine element..
        /// </summary>
        internal static string ErrorMessage_InvalidBindingTypeValueInStateMachineElement {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidBindingTypeValueInStateMachineElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Type value in History element..
        /// </summary>
        internal static string ErrorMessage_InvalidTypeValueInHistoryElement {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidTypeValueInHistoryElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location expression can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_LocationExpressionCantBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_LocationExpressionCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Location expression&apos; does not implement ILocationEvaluator..
        /// </summary>
        internal static string ErrorMessage_LocationExpressionDoesNotImplementILocationEvaluator {
            get {
                return ResourceManager.GetString("ErrorMessage_LocationExpressionDoesNotImplementILocationEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Location expression&apos; not supported in NULL data model..
        /// </summary>
        internal static string ErrorMessage_LocationExpressionNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMessage_LocationExpressionNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed required attributes &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMessage_MissedRequiredAttributes {
            get {
                return ResourceManager.GetString("ErrorMessage_MissedRequiredAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed required elements &lt;{0}&gt;..
        /// </summary>
        internal static string ErrorMessage_MissedRequiredElements {
            get {
                return ResourceManager.GetString("ErrorMessage_MissedRequiredElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be present at least Event or Condition or Target in Transition element..
        /// </summary>
        internal static string ErrorMessage_MustBePresentAtLeastEventOrConditionOrTargetInTransitionElement {
            get {
                return ResourceManager.GetString("ErrorMessage_MustBePresentAtLeastEventOrConditionOrTargetInTransitionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be present Event or EventExpression or Content in Send element..
        /// </summary>
        internal static string ErrorMessage_MustBePresentEventOrEventExpressionOrContentInSendElement {
            get {
                return ResourceManager.GetString("ErrorMessage_MustBePresentEventOrEventExpressionOrContentInSendElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name attributes required in Param element..
        /// </summary>
        internal static string ErrorMessage_NameAttributesRequiredInParamElement {
            get {
                return ResourceManager.GetString("ErrorMessage_NameAttributesRequiredInParamElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameList and Content can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_NameListAndContentCantBeUsedAtTheSameTimeInSendElement {
            get {
                return ResourceManager.GetString("ErrorMessage_NameListAndContentCantBeUsedAtTheSameTimeInSendElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameList and Parameters can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_NameListAndParametersCantBeUsedAtTheSameTimeInInvokeElement {
            get {
                return ResourceManager.GetString("ErrorMessage_NameListAndParametersCantBeUsedAtTheSameTimeInInvokeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one &lt;{0}&gt; element allowed..
        /// </summary>
        internal static string ErrorMessage_OnlyOneElementAllowed {
            get {
                return ResourceManager.GetString("ErrorMessage_OnlyOneElementAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters and Content can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_ParametersAndContentCantBeUsedAtTheSameTimeInSendElement {
            get {
                return ResourceManager.GetString("ErrorMessage_ParametersAndContentCantBeUsedAtTheSameTimeInSendElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise can&apos;t be used in Finalize element..
        /// </summary>
        internal static string ErrorMessage_RaiseCantBeUsedInFinalizeElement {
            get {
                return ResourceManager.GetString("ErrorMessage_RaiseCantBeUsedInFinalizeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuntimeAction and RuntimePredicate objects only allowed as action and condition in &apos;runtime&apos; data model..
        /// </summary>
        internal static string ErrorMessage_RuntimeActionAndPredicateOnlyAllowed {
            get {
                return ResourceManager.GetString("ErrorMessage_RuntimeActionAndPredicateOnlyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script expression can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_ScriptExpressionCantBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ScriptExpressionCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting not supported in NULL data model..
        /// </summary>
        internal static string ErrorMessage_ScriptingNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ScriptingNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting not supported in &apos;runtime&apos; data model..
        /// </summary>
        internal static string ErrorMessage_ScriptingNotSupportedInRuntimeDataModel {
            get {
                return ResourceManager.GetString("ErrorMessage_ScriptingNotSupportedInRuntimeDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting not supported in XPATH data model..
        /// </summary>
        internal static string ErrorMessage_ScriptingNotSupportedInXPATHDataModel {
            get {
                return ResourceManager.GetString("ErrorMessage_ScriptingNotSupportedInXPATHDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send can&apos;t be used in Finalize element..
        /// </summary>
        internal static string ErrorMessage_SendCantBeUsedInFinalizeElement {
            get {
                return ResourceManager.GetString("ErrorMessage_SendCantBeUsedInFinalizeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sendid attribute can&apos;t be empty in Cancel element..
        /// </summary>
        internal static string ErrorMessage_SendidAttributeCantBeEmptyInCancelElement {
            get {
                return ResourceManager.GetString("ErrorMessage_SendidAttributeCantBeEmptyInCancelElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sessionId] and [sessionIdExpr] attributes should not be assigned in Start element..
        /// </summary>
        internal static string ErrorMessage_SessionIdAndSessionIdExprAttributesShouldNotBeAssignedInStartElement {
            get {
                return ResourceManager.GetString("ErrorMessage_SessionIdAndSessionIdExprAttributesShouldNotBeAssignedInStartElement" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sessionId] could not be empty..
        /// </summary>
        internal static string ErrorMessage_SessionIdCouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorMessage_SessionIdCouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sessionId] or [sessionIdExpr] must be specified..
        /// </summary>
        internal static string ErrorMessage_SessionIdOrSessionIdExprMustBeSpecified {
            get {
                return ResourceManager.GetString("ErrorMessage_SessionIdOrSessionIdExprMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and Body can&apos;t be used at the same time in Assign element..
        /// </summary>
        internal static string ErrorMessage_SourceAndBodyCantBeUsedAtTheSameTimeInAssignElement {
            get {
                return ResourceManager.GetString("ErrorMessage_SourceAndBodyCantBeUsedAtTheSameTimeInAssignElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and SourceExpression can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_SourceAndSourceExpressionCantBeUsedAtTheSameTimeInInvokeElement {
            get {
                return ResourceManager.GetString("ErrorMessage_SourceAndSourceExpressionCantBeUsedAtTheSameTimeInInvokeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target and TargetExpression can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_TargetAndTargetExpressionCantBeUsedAtTheSameTimeInSendElement {
            get {
                return ResourceManager.GetString("ErrorMessage_TargetAndTargetExpressionCantBeUsedAtTheSameTimeInSendElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Id does not exists..
        /// </summary>
        internal static string ErrorMessage_TargetIdDoesNotExists {
            get {
                return ResourceManager.GetString("ErrorMessage_TargetIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition must be present in History element..
        /// </summary>
        internal static string ErrorMessage_TransitionMustBePresentInHistoryElement {
            get {
                return ResourceManager.GetString("ErrorMessage_TransitionMustBePresentInHistoryElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition must be present in Initial element..
        /// </summary>
        internal static string ErrorMessage_TransitionMustBePresentInInitialElement {
            get {
                return ResourceManager.GetString("ErrorMessage_TransitionMustBePresentInInitialElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type and TypeExpression can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_TypeAndTypeExpressionCantBeUsedAtTheSameTimeInInvokeElement {
            get {
                return ResourceManager.GetString("ErrorMessage_TypeAndTypeExpressionCantBeUsedAtTheSameTimeInInvokeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type and TypeExpression can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_TypeAndTypeExpressionCantBeUsedAtTheSameTimeInSendElement {
            get {
                return ResourceManager.GetString("ErrorMessage_TypeAndTypeExpressionCantBeUsedAtTheSameTimeInSendElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or TypeExpression must be specified in Invoke element..
        /// </summary>
        internal static string ErrorMessage_TypeOrTypeExpressionMustBeSpecifiedInInvokeElement {
            get {
                return ResourceManager.GetString("ErrorMessage_TypeOrTypeExpressionMustBeSpecifiedInInvokeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [url] and [urlExpr] attributes should not be assigned in Start element..
        /// </summary>
        internal static string ErrorMessage_UrlAndUrlExprAttributesShouldNotBeAssignedInStartElement {
            get {
                return ResourceManager.GetString("ErrorMessage_UrlAndUrlExprAttributesShouldNotBeAssignedInStartElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [url] has invalid URI format..
        /// </summary>
        internal static string ErrorMessage_UrlHasInvalidURIFormat {
            get {
                return ResourceManager.GetString("ErrorMessage_UrlHasInvalidURIFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Value expression&apos; does not implement IValueEvaluator..
        /// </summary>
        internal static string ErrorMessage_ValueExpressionDoesNotImplementIValueEvaluator {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueExpressionDoesNotImplementIValueEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Value expression&apos; not supported in NULL data model..
        /// </summary>
        internal static string ErrorMessage_ValueExpressionNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueExpressionNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml cannot be null..
        /// </summary>
        internal static string ErrorMessage_XmlCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_XmlCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access can&apos;t be changed..
        /// </summary>
        internal static string Exception_AccessCantBeChanged {
            get {
                return ResourceManager.GetString("Exception_AccessCantBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Permission [{0}] required..
        /// </summary>
        internal static string Exception_AccessDeniedPermissionRequired {
            get {
                return ResourceManager.GetString("Exception_AccessDeniedPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to IO bound threads denied..
        /// </summary>
        internal static string Exception_AccessToIOBoundThreadsDenied {
            get {
                return ResourceManager.GetString("Exception_AccessToIOBoundThreadsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another asynchronous operation in progress..
        /// </summary>
        internal static string Exception_AnotherAsynchronousOperationInProgress {
            get {
                return ResourceManager.GetString("Exception_AnotherAsynchronousOperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be DataModelDateTime type..
        /// </summary>
        internal static string Exception_ArgumentMustBeDataModelDateTimeType {
            get {
                return ResourceManager.GetString("Exception_ArgumentMustBeDataModelDateTimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion failed..
        /// </summary>
        internal static string Exception_AssertionFailed {
            get {
                return ResourceManager.GetString("Exception_AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find ResourceLoader to load external resource..
        /// </summary>
        internal static string Exception_CannotFindResourceLoaderToLoadExternalResource {
            get {
                return ResourceManager.GetString("Exception_CannotFindResourceLoaderToLoadExternalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find target..
        /// </summary>
        internal static string Exception_CannotFindTarget {
            get {
                return ResourceManager.GetString("Exception_CannotFindTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read raw content due to registered elements..
        /// </summary>
        internal static string Exception_CanNotReadRawContentDueToRegisteredElements {
            get {
                return ResourceManager.GetString("Exception_CanNotReadRawContentDueToRegisteredElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not register component due to registered raw content..
        /// </summary>
        internal static string Exception_CanNotRegisterComponentDueToRegisteredRawContent {
            get {
                return ResourceManager.GetString("Exception_CanNotRegisterComponentDueToRegisteredRawContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not register raw content more than one time..
        /// </summary>
        internal static string Exception_CanNotRegisterRawContentMoreThanOneTime {
            get {
                return ResourceManager.GetString("Exception_CanNotRegisterRawContentMoreThanOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find DataModelHandlerFactory for DataModel type &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_CantFindDataModelHandlerFactoryForDataModelType {
            get {
                return ResourceManager.GetString("Exception_CantFindDataModelHandlerFactoryForDataModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get access to IHost interface..
        /// </summary>
        internal static string Exception_CantGetAccessToIHostInterface {
            get {
                return ResourceManager.GetString("Exception_CantGetAccessToIHostInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t match network interface to listen..
        /// </summary>
        internal static string Exception_CantMatchNetworkInterfaceToListen {
            get {
                return ResourceManager.GetString("Exception_CantMatchNetworkInterfaceToListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t restore element..
        /// </summary>
        internal static string Exception_CantRestoreElement {
            get {
                return ResourceManager.GetString("Exception_CantRestoreElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel can&apos;t consume previously persisted object..
        /// </summary>
        internal static string Exception_ChannelCantConsumePreviouslyPersistedObject {
            get {
                return ResourceManager.GetString("Exception_ChannelCantConsumePreviouslyPersistedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition does not specified..
        /// </summary>
        internal static string Exception_ConditionDoesNotSpecified {
            get {
                return ResourceManager.GetString("Exception_ConditionDoesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom action does not supported..
        /// </summary>
        internal static string Exception_CustomActionDoesNotSupported {
            get {
                return ResourceManager.GetString("Exception_CustomActionDoesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle reference detected..
        /// </summary>
        internal static string Exception_CycleReferenceDetected {
            get {
                return ResourceManager.GetString("Exception_CycleReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data format not supported..
        /// </summary>
        internal static string Exception_DataFormatNotSupported {
            get {
                return ResourceManager.GetString("Exception_DataFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not Boolean..
        /// </summary>
        internal static string Exception_DataModelValueIsNotBoolean {
            get {
                return ResourceManager.GetString("Exception_DataModelValueIsNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not DataModelList..
        /// </summary>
        internal static string Exception_DataModelValueIsNotDataModelList {
            get {
                return ResourceManager.GetString("Exception_DataModelValueIsNotDataModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not DateTime..
        /// </summary>
        internal static string Exception_DataModelValueIsNotDateTime {
            get {
                return ResourceManager.GetString("Exception_DataModelValueIsNotDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not Number..
        /// </summary>
        internal static string Exception_DataModelValueIsNotNumber {
            get {
                return ResourceManager.GetString("Exception_DataModelValueIsNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not String..
        /// </summary>
        internal static string Exception_DataModelValueIsNotString {
            get {
                return ResourceManager.GetString("Exception_DataModelValueIsNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay parsing error. Format is ###0(ms|s)..
        /// </summary>
        internal static string Exception_DelayParsingError {
            get {
                return ResourceManager.GetString("Exception_DelayParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination list is not long enough to copy all the items in the collection. Check list index and length..
        /// </summary>
        internal static string Exception_DestinationArrayIsNotLongEnough {
            get {
                return ResourceManager.GetString("Exception_DestinationArrayIsNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on event consumer side. Exception message: {0}.
        ///{1}.
        /// </summary>
        internal static string Exception_ErrorOnEventConsumerSide {
            get {
                return ResourceManager.GetString("Exception_ErrorOnEventConsumerSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on parsing XPath expression..
        /// </summary>
        internal static string Exception_ErrorOnParsingXPathExpression {
            get {
                return ResourceManager.GetString("Exception_ErrorOnParsingXPathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event dispatcher not found..
        /// </summary>
        internal static string Exception_EventDispatcherNotFound {
            get {
                return ResourceManager.GetString("Exception_EventDispatcherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Target did not specified..
        /// </summary>
        internal static string Exception_EventTargetDidNotSpecified {
            get {
                return ResourceManager.GetString("Exception_EventTargetDidNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External communication does not configured for state machine interpreter..
        /// </summary>
        internal static string Exception_ExternalCommunicationDoesNotConfiguredForStateMachineInterpreter {
            get {
                return ResourceManager.GetString("Exception_ExternalCommunicationDoesNotConfiguredForStateMachineInterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward entities required to restore state machine..
        /// </summary>
        internal static string Exception_ForwardEntitiesRequiredToRestoreStateMachine {
            get {
                return ResourceManager.GetString("Exception_ForwardEntitiesRequiredToRestoreStateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward entity can not be found..
        /// </summary>
        internal static string Exception_ForwardEntityCanNotBeFound {
            get {
                return ResourceManager.GetString("Exception_ForwardEntityCanNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward entity has incorrect type..
        /// </summary>
        internal static string Exception_ForwardEntityHasIncorrectType {
            get {
                return ResourceManager.GetString("Exception_ForwardEntityHasIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found more then one interface to listen..
        /// </summary>
        internal static string Exception_FoundMoreThenOneInterfaceToListen {
            get {
                return ResourceManager.GetString("Exception_FoundMoreThenOneInterfaceToListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier cannot contains whitespace..
        /// </summary>
        internal static string Exception_IdentifierCannotContainsWhitespace {
            get {
                return ResourceManager.GetString("Exception_IdentifierCannotContainsWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data format..
        /// </summary>
        internal static string Exception_IncorrectDataFormat {
            get {
                return ResourceManager.GetString("Exception_IncorrectDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect encoding..
        /// </summary>
        internal static string Exception_IncorrectEncoding {
            get {
                return ResourceManager.GetString("Exception_IncorrectEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index should be non-negative and less then array size..
        /// </summary>
        internal static string Exception_IndexShouldBeNonNegativeAndLessThenAarraySize {
            get {
                return ResourceManager.GetString("Exception_IndexShouldBeNonNegativeAndLessThenAarraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index value must be non-negative integer..
        /// </summary>
        internal static string Exception_IndexValueMustBeNonNegativeInteger {
            get {
                return ResourceManager.GetString("Exception_IndexValueMustBeNonNegativeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIncludeReader does not support in-document references..
        /// </summary>
        internal static string Exception_IndocumentReferencesNotSupported {
            get {
                return ResourceManager.GetString("Exception_IndocumentReferencesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal events can&apos;t be delayed..
        /// </summary>
        internal static string Exception_InternalEventsCantBeDelayed {
            get {
                return ResourceManager.GetString("Exception_InternalEventsCantBeDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InvokeId..
        /// </summary>
        internal static string Exception_InvalidInvokeId {
            get {
                return ResourceManager.GetString("Exception_InvalidInvokeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type..
        /// </summary>
        internal static string Exception_InvalidType {
            get {
                return ResourceManager.GetString("Exception_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TypeInfo value..
        /// </summary>
        internal static string Exception_InvalidTypeInfoValue {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeInfoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_InvalidURI {
            get {
                return ResourceManager.GetString("Exception_InvalidURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed InvokeId..
        /// </summary>
        internal static string Exception_InvokedServiceMetaMissedInvokeId {
            get {
                return ResourceManager.GetString("Exception_InvokedServiceMetaMissedInvokeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Processor has not been started..
        /// </summary>
        internal static string Exception_IOProcessorHasNotBeenStarted {
            get {
                return ResourceManager.GetString("Exception_IOProcessorHasNotBeenStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item can&apos;t be null..
        /// </summary>
        internal static string Exception_ItemCantBeNull {
            get {
                return ResourceManager.GetString("Exception_ItemCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; key not found..
        /// </summary>
        internal static string Exception_KeyNotFound {
            get {
                return ResourceManager.GetString("Exception_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key should not be empty.
        /// </summary>
        internal static string Exception_KeyShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_KeyShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of events cannot be empty..
        /// </summary>
        internal static string Exception_ListOfEventsCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ListOfEventsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of identifiers cannot be empty..
        /// </summary>
        internal static string Exception_ListOfIdentifiersCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ListOfIdentifiersCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of locations cannot be empty..
        /// </summary>
        internal static string Exception_ListOfLocationsCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ListOfLocationsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading external resources does not supported. Derive class from ScxmlXmlResolver and pass instance of it to ScxmlDirector..
        /// </summary>
        internal static string Exception_LoadingExternalResourcesDoesNotSupported {
            get {
                return ResourceManager.GetString("Exception_LoadingExternalResourcesDoesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location does not specified..
        /// </summary>
        internal static string Exception_LocationDoesNotSpecified {
            get {
                return ResourceManager.GetString("Exception_LocationDoesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed ParentSessionId..
        /// </summary>
        internal static string Exception_MissedParentSessionId {
            get {
                return ResourceManager.GetString("Exception_MissedParentSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed SessionId..
        /// </summary>
        internal static string Exception_MissedSessionId {
            get {
                return ResourceManager.GetString("Exception_MissedSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message read partially. {0} of {1} bytes..
        /// </summary>
        internal static string Exception_NamedIoProcessorMessageReadPartially {
            get {
                return ResourceManager.GetString("Exception_NamedIoProcessorMessageReadPartially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message size has wrong value or missed. Size: {0} bytes..
        /// </summary>
        internal static string Exception_NamedIoProcessorMessageSizeHasWrongValueOrMissed {
            get {
                return ResourceManager.GetString("Exception_NamedIoProcessorMessageSizeHasWrongValueOrMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedIoProcessor with name &apos;{0}&apos; already has been registered..
        /// </summary>
        internal static string Exception_NamedIoProcessorWithNameAlreadyHasBeenRegistered {
            get {
                return ResourceManager.GetString("Exception_NamedIoProcessorWithNameAlreadyHasBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting level reached, probably circular inclusion..
        /// </summary>
        internal static string Exception_NestingReachedLevelInclusion {
            get {
                return ResourceManager.GetString("Exception_NestingReachedLevelInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not expected token type..
        /// </summary>
        internal static string Exception_NotExpectedTokenType {
            get {
                return ResourceManager.GetString("Exception_NotExpectedTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object can not be modified..
        /// </summary>
        internal static string Exception_ObjectCanNotBeModified {
            get {
                return ResourceManager.GetString("Exception_ObjectCanNotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition argument should be null..
        /// </summary>
        internal static string Exception_PartitionArgumentShouldBeNull {
            get {
                return ResourceManager.GetString("Exception_PartitionArgumentShouldBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persisted state can&apos;t be read. Stored and provided SessionIds does not match..
        /// </summary>
        internal static string Exception_PersistedStateCantBeReadStoredAndProvidedSessionIdsDoesNotMatch {
            get {
                return ResourceManager.GetString("Exception_PersistedStateCantBeReadStoredAndProvidedSessionIdsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persisted state can&apos;t be read. Unsupported version..
        /// </summary>
        internal static string Exception_PersistedStateCantBeReadUnsupportedVersion {
            get {
                return ResourceManager.GetString("Exception_PersistedStateCantBeReadUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix {0} can&apos;t be resolved..
        /// </summary>
        internal static string Exception_PrefixCantBeResolved {
            get {
                return ResourceManager.GetString("Exception_PrefixCantBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration should no occur after initialization..
        /// </summary>
        internal static string Exception_RegistrationShouldNoOccurAfterInitialization {
            get {
                return ResourceManager.GetString("Exception_RegistrationShouldNoOccurAfterInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; not found..
        /// </summary>
        internal static string Exception_ResourceNotFound {
            get {
                return ResourceManager.GetString("Exception_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of XPath expression can&apos;t be identified..
        /// </summary>
        internal static string Exception_ResultOfXPathExpressionCantBeIdentified {
            get {
                return ResourceManager.GetString("Exception_ResultOfXPathExpressionCantBeIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of XPath expression should be boolean value..
        /// </summary>
        internal static string Exception_ResultOfXPathExpressionShouldBeBooleanValue {
            get {
                return ResourceManager.GetString("Exception_ResultOfXPathExpressionShouldBeBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of XPath expression should be element..
        /// </summary>
        internal static string Exception_ResultOfXPathExpressionShouldBeElement {
            get {
                return ResourceManager.GetString("Exception_ResultOfXPathExpressionShouldBeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path can be set only before visiting..
        /// </summary>
        internal static string Exception_RootPathCanBeSetOnlyBeforeVisiting {
            get {
                return ResourceManager.GetString("Exception_RootPathCanBeSetOnlyBeforeVisiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendId is empty..
        /// </summary>
        internal static string Exception_SendIdIsEmpty {
            get {
                return ResourceManager.GetString("Exception_SendIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId could not be empty..
        /// </summary>
        internal static string Exception_SessionIdCouldNotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_SessionIdCouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified method is not supported in type {0}..
        /// </summary>
        internal static string Exception_SpecifiedMethodIsNotSupportedInType {
            get {
                return ResourceManager.GetString("Exception_SpecifiedMethodIsNotSupportedInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source not specified..
        /// </summary>
        internal static string Exception_StartActionExecuteSourceNotSpecified {
            get {
                return ResourceManager.GetString("Exception_StartActionExecuteSourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting State Machine denied..
        /// </summary>
        internal static string Exception_StartingStateMachineDenied {
            get {
                return ResourceManager.GetString("Exception_StartingStateMachineDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateId not initialized..
        /// </summary>
        internal static string Exception_StateIdNotInitialized {
            get {
                return ResourceManager.GetString("Exception_StateIdNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine external queue has been closed..
        /// </summary>
        internal static string Exception_StateMachineExternalQueueHasBeenClosed {
            get {
                return ResourceManager.GetString("Exception_StateMachineExternalQueueHasBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine has been destroyed..
        /// </summary>
        internal static string Exception_StateMachineHasBeenDestroyed {
            get {
                return ResourceManager.GetString("Exception_StateMachineHasBeenDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine has been halted..
        /// </summary>
        internal static string Exception_StateMachineHasBeenHalted {
            get {
                return ResourceManager.GetString("Exception_StateMachineHasBeenHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine has been suspended..
        /// </summary>
        internal static string Exception_StateMachineHasBeenSuspended {
            get {
                return ResourceManager.GetString("Exception_StateMachineHasBeenSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachineHost stopped..
        /// </summary>
        internal static string Exception_StateMachineHostStopped {
            get {
                return ResourceManager.GetString("Exception_StateMachineHostStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachine origin missed..
        /// </summary>
        internal static string Exception_StateMachineOriginMissed {
            get {
                return ResourceManager.GetString("Exception_StateMachineOriginMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message #{0} of {1}: {2}.
        /// </summary>
        internal static string Exception_StateMachineValidationExceptionMessage {
            get {
                return ResourceManager.GetString("Exception_StateMachineValidationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage not available for read operations.
        /// </summary>
        internal static string Exception_StorageNotAvailableForReadOperations {
            get {
                return ResourceManager.GetString("Exception_StorageNotAvailableForReadOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream should support Read, Write, Seek operations..
        /// </summary>
        internal static string Exception_StreamShouldSupportReadWriteSeekOperations {
            get {
                return ResourceManager.GetString("Exception_StreamShouldSupportReadWriteSeekOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target is not defined.
        /// </summary>
        internal static string Exception_TargetIsNotDefined {
            get {
                return ResourceManager.GetString("Exception_TargetIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target should be equal to &apos;Parent&apos; or null..
        /// </summary>
        internal static string Exception_TargetShouldBeEqualToParentOrNull {
            get {
                return ResourceManager.GetString("Exception_TargetShouldBeEqualToParentOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target wrong format..
        /// </summary>
        internal static string Exception_TargetWrongFormat {
            get {
                return ResourceManager.GetString("Exception_TargetWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can&apos;t be found in type &apos;{1}&apos; or in its ancestors..
        /// </summary>
        internal static string Exception_TypeCantBeFound {
            get {
                return ResourceManager.GetString("Exception_TypeCantBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type, SendId, DelayMs can&apos;t be specified for this event..
        /// </summary>
        internal static string Exception_TypeSendIdDelayMsCantBeSpecifiedForThisEvent {
            get {
                return ResourceManager.GetString("Exception_TypeSendIdDelayMsCantBeSpecifiedForThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined value not allowed..
        /// </summary>
        internal static string Exception_UndefinedValueNotAllowed {
            get {
                return ResourceManager.GetString("Exception_UndefinedValueNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type attribute value: {0}..
        /// </summary>
        internal static string Exception_UnexpectedTypeAttributeValue {
            get {
                return ResourceManager.GetString("Exception_UnexpectedTypeAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected TypeInfo value.
        ///.
        /// </summary>
        internal static string Exception_UnexpectedTypeInfoValue {
            get {
                return ResourceManager.GetString("Exception_UnexpectedTypeInfoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value..
        /// </summary>
        internal static string Exception_UnexpectedValue {
            get {
                return ResourceManager.GetString("Exception_UnexpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception..
        /// </summary>
        internal static string Exception_UnhandledException {
            get {
                return ResourceManager.GetString("Exception_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Condition type..
        /// </summary>
        internal static string Exception_UnknownConditionType {
            get {
                return ResourceManager.GetString("Exception_UnknownConditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Executable Entity type..
        /// </summary>
        internal static string Exception_UnknownExecutableEntityType {
            get {
                return ResourceManager.GetString("Exception_UnknownExecutableEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown &apos;parse&apos; attribute value: &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_UnknownParseAttrValue {
            get {
                return ResourceManager.GetString("Exception_UnknownParseAttrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown State Entity type..
        /// </summary>
        internal static string Exception_UnknownStateEntityType {
            get {
                return ResourceManager.GetString("Exception_UnknownStateEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type for serialization..
        /// </summary>
        internal static string Exception_UnknownTypeForSerialization {
            get {
                return ResourceManager.GetString("Exception_UnknownTypeForSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown XPath function. Namespace:&apos;{0}&apos;, Name:&apos;{1}&apos;..
        /// </summary>
        internal static string Exception_UnknownXPathFunction {
            get {
                return ResourceManager.GetString("Exception_UnknownXPathFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown XPath variable. Namespace:&apos;{0}&apos;, Name:&apos;{1}&apos;..
        /// </summary>
        internal static string Exception_UnknownXPathVariable {
            get {
                return ResourceManager.GetString("Exception_UnknownXPathVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve URI reference &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_UnresolvableURI {
            get {
                return ResourceManager.GetString("Exception_UnresolvableURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedirectXmlResolver not supported class: {0}..
        /// </summary>
        internal static string Exception_UnsupportedClass {
            get {
                return ResourceManager.GetString("Exception_UnsupportedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported object type..
        /// </summary>
        internal static string Exception_UnsupportedObjectType {
            get {
                return ResourceManager.GetString("Exception_UnsupportedObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SCXML version..
        /// </summary>
        internal static string Exception_UnsupportedScxmlVersion {
            get {
                return ResourceManager.GetString("Exception_UnsupportedScxmlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported {0} type: [{1}]..
        /// </summary>
        internal static string Exception_UnsupportedType {
            get {
                return ResourceManager.GetString("Exception_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ReadAsync() instead..
        /// </summary>
        internal static string Exception_UseReadAsyncInstead {
            get {
                return ResourceManager.GetString("Exception_UseReadAsyncInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use WriteAsync() instead..
        /// </summary>
        internal static string Exception_UseWriteAsyncInstead {
            get {
                return ResourceManager.GetString("Exception_UseWriteAsyncInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be an empty collection..
        /// </summary>
        internal static string Exception_ValueCannotBeAnEmptyCollection {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeAnEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be an empty list..
        /// </summary>
        internal static string Exception_ValueCannotBeAnEmptyList {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeAnEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty list..
        /// </summary>
        internal static string Exception_ValueCannotBeEmptyList {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string Exception_ValueCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be parsed for type {0}..
        /// </summary>
        internal static string Exception_ValueCannotBeParsed {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be empty..
        /// </summary>
        internal static string Exception_ValueCantBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ValueCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression must be present..
        /// </summary>
        internal static string Exception_ValueExpressionMustBePresent {
            get {
                return ResourceManager.GetString("Exception_ValueExpressionMustBePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not SCXML..
        /// </summary>
        internal static string Exception_ValueIsNotSCXML {
            get {
                return ResourceManager.GetString("Exception_ValueIsNotSCXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not Source..
        /// </summary>
        internal static string Exception_ValueIsNotSource {
            get {
                return ResourceManager.GetString("Exception_ValueIsNotSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not StateMachine..
        /// </summary>
        internal static string Exception_ValueIsNotStateMachine {
            get {
                return ResourceManager.GetString("Exception_ValueIsNotStateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be non negative integer..
        /// </summary>
        internal static string Exception_ValueMustBeNonNegativeInteger {
            get {
                return ResourceManager.GetString("Exception_ValueMustBeNonNegativeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Line {1}, Position {2}..
        /// </summary>
        internal static string Exception_XIncludeExceptionLinePosition {
            get {
                return ResourceManager.GetString("Exception_XIncludeExceptionLinePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Location: {1}..
        /// </summary>
        internal static string Exception_XIncludeExceptionLocation {
            get {
                return ResourceManager.GetString("Exception_XIncludeExceptionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Location: {1}, Line {2}, Position {3}..
        /// </summary>
        internal static string Exception_XIncludeExceptionLocationLinePosition {
            get {
                return ResourceManager.GetString("Exception_XIncludeExceptionLocationLinePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occurred during GetEntity call to XmlResolver..
        /// </summary>
        internal static string Exception_XmlResolverGetEntity {
            get {
                return ResourceManager.GetString("Exception_XmlResolverGetEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlResolver returned null..
        /// </summary>
        internal static string Exception_XmlResolverReturnedNull {
            get {
                return ResourceManager.GetString("Exception_XmlResolverReturnedNull", resourceCulture);
            }
        }
    }
}
