//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtate.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom action does not configured..
        /// </summary>
        internal static string Assertion_CustomActionDoesNotConfigured {
            get {
                return ResourceManager.GetString("Assertion_CustomActionDoesNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects structure mismatch..
        /// </summary>
        internal static string Assertion_ObjectsStructureMismatch {
            get {
                return ResourceManager.GetString("Assertion_ObjectsStructureMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: [{0}]. Name: [{1}]. SessionId: [{2}]. SourceEntityId: [{3}]. Exception: {4}.
        /// </summary>
        internal static string DefaultLogger_LogError {
            get {
                return ResourceManager.GetString("DefaultLogger_LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: [{0}]. SessionId: [{1}]. Label: &quot;{2}&quot;. Data: {3}.
        /// </summary>
        internal static string DefaultLogger_LogInfo {
            get {
                return ResourceManager.GetString("DefaultLogger_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel event. SendId: [{0}]..
        /// </summary>
        internal static string DefaultLogger_TraceCancelEvent {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceCancelEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel invoke. InvokeId: [{0}]..
        /// </summary>
        internal static string DefaultLogger_TraceCancelInvoke {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceCancelInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered to state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceEnteredState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceEnteredState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering to state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceEnteringState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceEnteringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exited from state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceExitedState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceExitedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting from state: [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceExitingState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceExitingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreter state has changed to [{0}]. SessionId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceInterpreterState {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceInterpreterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed {0} transition to: [{1}]. Event: [{2}]. SessionId: [{3}]..
        /// </summary>
        internal static string DefaultLogger_TracePerformedTransition {
            get {
                return ResourceManager.GetString("DefaultLogger_TracePerformedTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing {0} transition to: [{1}]. Event: [{2}]. SessionId: [{3}]..
        /// </summary>
        internal static string DefaultLogger_TracePerformingTransition {
            get {
                return ResourceManager.GetString("DefaultLogger_TracePerformingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} event [{1}]. SendId: [{2}]. InvokeId: [{3}]. Data: [{4}]. OriginType: [{5}]. Origin: [{6}]. SessionId: [{7}]..
        /// </summary>
        internal static string DefaultLogger_TraceProcessingEvent {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceProcessingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send event: [{0}]. SendId: [{1}]..
        /// </summary>
        internal static string DefaultLogger_TraceSendEvent {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceSendEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start invoke. InvokeId: [{0}]..
        /// </summary>
        internal static string DefaultLogger_TraceStartInvoke {
            get {
                return ResourceManager.GetString("DefaultLogger_TraceStartInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModel not supported in NULL data model..
        /// </summary>
        internal static string ErrorMesasge_DataModelNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMesasge_DataModelNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoneData not supported in NULL data model..
        /// </summary>
        internal static string ErrorMesasge_DoneDataNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMesasge_DoneDataNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForEach not supported in NULL data model..
        /// </summary>
        internal static string ErrorMesasge_ForEachNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMesasge_ForEachNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect condition expression..
        /// </summary>
        internal static string ErrorMesasge_IncorrectConditionExpression {
            get {
                return ResourceManager.GetString("ErrorMesasge_IncorrectConditionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format of condition expression for NULL data model..
        /// </summary>
        internal static string ErrorMesasge_IncorrectConditionExpressionForNull {
            get {
                return ResourceManager.GetString("ErrorMesasge_IncorrectConditionExpressionForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Location expression&apos; not supported in NULL data model..
        /// </summary>
        internal static string ErrorMesasge_LocationExpressionNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMesasge_LocationExpressionNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting not supported in NULL data model..
        /// </summary>
        internal static string ErrorMesasge_ScriptingNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMesasge_ScriptingNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Value expression&apos; not supported in NULL data model..
        /// </summary>
        internal static string ErrorMesasge_ValueExpressionNotSupportedForNull {
            get {
                return ResourceManager.GetString("ErrorMesasge_ValueExpressionNotSupportedForNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array property required for ForEach element.
        /// </summary>
        internal static string ErrorMessage_ArrayPropertyRequiredForForEach {
            get {
                return ResourceManager.GetString("ErrorMessage_ArrayPropertyRequiredForForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression or Inline content should be specified in Assign element..
        /// </summary>
        internal static string ErrorMessage_AssignItemContentAndExpressionMissed {
            get {
                return ResourceManager.GetString("ErrorMessage_AssignItemContentAndExpressionMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Inline content can&apos;t be used at the same time in Assign element..
        /// </summary>
        internal static string ErrorMessage_AssignItemContentAndExpressionSpecified {
            get {
                return ResourceManager.GetString("ErrorMessage_AssignItemContentAndExpressionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location missed in Assign element..
        /// </summary>
        internal static string ErrorMessage_AssignItemLocationMissed {
            get {
                return ResourceManager.GetString("ErrorMessage_AssignItemLocationMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one attribute url or urlExpr must be specified.
        /// </summary>
        internal static string ErrorMessage_At_least_one_url_must_be_specified {
            get {
                return ResourceManager.GetString("ErrorMessage_At_least_one_url_must_be_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attr attribute should no be empty..
        /// </summary>
        internal static string ErrorMessage_attr_attribute_should_no_be_empty {
            get {
                return ResourceManager.GetString("ErrorMessage_attr_attribute_should_no_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendId or SendIdExpression should be specified in Cancel element..
        /// </summary>
        internal static string ErrorMessage_CancelItemSendIdAndExpressionMissed {
            get {
                return ResourceManager.GetString("ErrorMessage_CancelItemSendIdAndExpressionMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendId and SendIdExpression can&apos;t be used at the same time in Cancel element..
        /// </summary>
        internal static string ErrorMessage_CancelItemSendIdAndExpressionSpecified {
            get {
                return ResourceManager.GetString("ErrorMessage_CancelItemSendIdAndExpressionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition expression can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_ConditionExpressionCantBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionExpressionCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition property required for ElseIf element..
        /// </summary>
        internal static string ErrorMessage_ConditionRequiredForElseIf {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionRequiredForElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition property required for ForEach element..
        /// </summary>
        internal static string ErrorMessage_ConditionRequiredForForEach {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionRequiredForForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition property required for If element..
        /// </summary>
        internal static string ErrorMessage_ConditionRequiredForIf {
            get {
                return ResourceManager.GetString("ErrorMessage_ConditionRequiredForIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content value can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_ContentValueCantBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ContentValueCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom action executor can&apos;t be found..
        /// </summary>
        internal static string ErrorMessage_Custom_action_executor_can_t_be_found {
            get {
                return ResourceManager.GetString("ErrorMessage_Custom_action_executor_can_t_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModel not supported in &apos;runtime&apos; data model..
        /// </summary>
        internal static string ErrorMessage_DataModelNotSupportedInRuntime {
            get {
                return ResourceManager.GetString("ErrorMessage_DataModelNotSupportedInRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected unknown element &lt;{0}&gt;..
        /// </summary>
        internal static string ErrorMessage_DetectedUnknownElement {
            get {
                return ResourceManager.GetString("ErrorMessage_DetectedUnknownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;else&gt; can be used only once..
        /// </summary>
        internal static string ErrorMessage_ElseCanBeUsedOnlyOnce {
            get {
                return ResourceManager.GetString("ErrorMessage_ElseCanBeUsedOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;elseif&gt; can not follow &lt;else&gt;..
        /// </summary>
        internal static string ErrorMessage_ElseifCannotFollowElse {
            get {
                return ResourceManager.GetString("ErrorMessage_ElseifCannotFollowElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on creation CustomAction executor..
        /// </summary>
        internal static string ErrorMessage_Error_on_creation_CustomAction_executor {
            get {
                return ResourceManager.GetString("ErrorMessage_Error_on_creation_CustomAction_executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event, EventExpression and Content can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_EvenExpressionContentInSend {
            get {
                return ResourceManager.GetString("ErrorMessage_EvenExpressionContentInSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event and EventExpression can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_EventExpressionInSend {
            get {
                return ResourceManager.GetString("ErrorMessage_EventExpressionInSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event property required for Raise element..
        /// </summary>
        internal static string ErrorMessage_EventRequiredForRaise {
            get {
                return ResourceManager.GetString("ErrorMessage_EventRequiredForRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected element &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ErrorMessage_ExpectedElementNotFound {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpectedElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression or Body should be specified in Content element..
        /// </summary>
        internal static string ErrorMessage_ExpressionAndBodyMissedInContent {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionAndBodyMissedInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Body can&apos;t be used at the same time in Content element..
        /// </summary>
        internal static string ErrorMessage_ExpressionAndBodySpecifiedInContent {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionAndBodySpecifiedInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Location can&apos;t be used at the same time in Param element..
        /// </summary>
        internal static string ErrorMessage_ExpressionLocationInParam {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionLocationInParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression and Source and Inline content can&apos;t be used at the same time in Data element..
        /// </summary>
        internal static string ErrorMessage_ExpressionSourceInData {
            get {
                return ResourceManager.GetString("ErrorMessage_ExpressionSourceInData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure on attribute processing..
        /// </summary>
        internal static string ErrorMessage_FailureAttributeProcessing {
            get {
                return ResourceManager.GetString("ErrorMessage_FailureAttributeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure on raw content processing..
        /// </summary>
        internal static string ErrorMessage_FailureContentProcessing {
            get {
                return ResourceManager.GetString("ErrorMessage_FailureContentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure on element processing..
        /// </summary>
        internal static string ErrorMessage_FailureElementProcessing {
            get {
                return ResourceManager.GetString("ErrorMessage_FailureElementProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found duplicate attribute &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMessage_FoundDuplicateAttribute {
            get {
                return ResourceManager.GetString("ErrorMessage_FoundDuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id and IdLocation can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_Id_and_IdLocation_can_t_be_used_at_the_same_time_in_Invoke_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Id_and_IdLocation_can_t_be_used_at_the_same_time_in_Invoke_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id and IdLocation can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_Id_and_IdLocation_can_t_be_used_at_the_same_time_in_Send_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Id_and_IdLocation_can_t_be_used_at_the_same_time_in_Send_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id property required in Data element..
        /// </summary>
        internal static string ErrorMessage_Id_property_required_in_Data_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Id_property_required_in_Data_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state/property can be used only in complex (compound) states..
        /// </summary>
        internal static string ErrorMessage_Initial_state_property_can_be_used_only_in_complex_states {
            get {
                return ResourceManager.GetString("ErrorMessage_Initial_state_property_can_be_used_only_in_complex_states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state/property cannot be used without any states..
        /// </summary>
        internal static string ErrorMessage_Initial_state_property_cannot_be_used_without_any_states {
            get {
                return ResourceManager.GetString("ErrorMessage_Initial_state_property_cannot_be_used_without_any_states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial attribute and Initial state can&apos;t be used at the same time in State element..
        /// </summary>
        internal static string ErrorMessage_InitialAttributeAndInitialStateCantBeUsedAtTheSameTimeInStateElement {
            get {
                return ResourceManager.GetString("ErrorMessage_InitialAttributeAndInitialStateCantBeUsedAtTheSameTimeInStateElement" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BindingType value in StateMachine element..
        /// </summary>
        internal static string ErrorMessage_Invalid_BindingType_value_in_StateMachine_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Invalid_BindingType_value_in_StateMachine_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Type value in History element..
        /// </summary>
        internal static string ErrorMessage_Invalid_Type_value_in_History_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Invalid_Type_value_in_History_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Location expression&apos; does not implement ILocationEvaluator..
        /// </summary>
        internal static string ErrorMessage_Location_expression__does_not_implement_ILocationEvaluator {
            get {
                return ResourceManager.GetString("ErrorMessage_Location_expression__does_not_implement_ILocationEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location expression can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_Location_expression_can_t_be_null {
            get {
                return ResourceManager.GetString("ErrorMessage_Location_expression_can_t_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed required attributes &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMessage_Missed_required_attributes {
            get {
                return ResourceManager.GetString("ErrorMessage_Missed_required_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed required elements &lt;{0}&gt;..
        /// </summary>
        internal static string ErrorMessage_Missed_required_elements {
            get {
                return ResourceManager.GetString("ErrorMessage_Missed_required_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be present at least Event or Condition or Target in Transition element..
        /// </summary>
        internal static string ErrorMessage_Must_be_present_at_least_Event_or_Condition_or_Target_in_Transition_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Must_be_present_at_least_Event_or_Condition_or_Target_in_Transition_" +
                        "element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be present Event or EventExpression or Content in Send element..
        /// </summary>
        internal static string ErrorMessage_Must_be_present_Event_or_EventExpression_or_Content_in_Send_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Must_be_present_Event_or_EventExpression_or_Content_in_Send_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name attributes required in Param element..
        /// </summary>
        internal static string ErrorMessage_Name_attributes_required_in_Param_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Name_attributes_required_in_Param_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameList and Content can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_NameList_and_Content_can_t_be_used_at_the_same_time_in_Send_element {
            get {
                return ResourceManager.GetString("ErrorMessage_NameList_and_Content_can_t_be_used_at_the_same_time_in_Send_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameList and Parameters can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_NameList_and_Parameters_can_t_be_used_at_the_same_time_in_Invoke_element {
            get {
                return ResourceManager.GetString("ErrorMessage_NameList_and_Parameters_can_t_be_used_at_the_same_time_in_Invoke_ele" +
                        "ment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one &lt;{0}&gt; element allowed..
        /// </summary>
        internal static string ErrorMessage_Only_one_element_allowed {
            get {
                return ResourceManager.GetString("ErrorMessage_Only_one_element_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters and Content can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_Parameters_and_Content_can_t_be_used_at_the_same_time_in_Send_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Parameters_and_Content_can_t_be_used_at_the_same_time_in_Send_elemen" +
                        "t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise can&apos;t be used in Finalize element..
        /// </summary>
        internal static string ErrorMessage_Raise_can_t_be_used_in_Finalize_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Raise_can_t_be_used_in_Finalize_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuntimeAction and RuntimePredicate objects only allowed as action and condition in &apos;runtime&apos; data model..
        /// </summary>
        internal static string ErrorMessage_RuntimeActionAndPredicateOnlyAllowed {
            get {
                return ResourceManager.GetString("ErrorMessage_RuntimeActionAndPredicateOnlyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script expression can&apos;t be null..
        /// </summary>
        internal static string ErrorMessage_Script_expression_can_t_be_null {
            get {
                return ResourceManager.GetString("ErrorMessage_Script_expression_can_t_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting not supported in XPATH data model..
        /// </summary>
        internal static string ErrorMessage_Scripting_not_supported_in_XPATH_data_model {
            get {
                return ResourceManager.GetString("ErrorMessage_Scripting_not_supported_in_XPATH_data_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting not supported in &apos;runtime&apos; data model..
        /// </summary>
        internal static string ErrorMessage_ScriptingNotSupportedInRuntimeDataModel {
            get {
                return ResourceManager.GetString("ErrorMessage_ScriptingNotSupportedInRuntimeDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send can&apos;t be used in Finalize element..
        /// </summary>
        internal static string ErrorMessage_Send_can_t_be_used_in_Finalize_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Send_can_t_be_used_in_Finalize_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sendid attribute can&apos;t be empty in Cancel element..
        /// </summary>
        internal static string ErrorMessage_SendidAttributeCantBeEmptyInCancelElement {
            get {
                return ResourceManager.GetString("ErrorMessage_SendidAttributeCantBeEmptyInCancelElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sessionId] and [sessionIdExpr] attributes should not be assigned in Start element..
        /// </summary>
        internal static string ErrorMessage_sessionId__and__sessionIdExpr__attributes_should_not_be_assigned_in_Start_element {
            get {
                return ResourceManager.GetString("ErrorMessage_sessionId__and__sessionIdExpr__attributes_should_not_be_assigned_in_" +
                        "Start_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sessionId] or [sessionIdExpr] must be specified..
        /// </summary>
        internal static string ErrorMessage_sessionId__or__sessionIdExpr__must_be_specified {
            get {
                return ResourceManager.GetString("ErrorMessage_sessionId__or__sessionIdExpr__must_be_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sessionId] could not be empty..
        /// </summary>
        internal static string ErrorMessage_SessionId_could_not_be_empty {
            get {
                return ResourceManager.GetString("ErrorMessage_SessionId_could_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and Body can&apos;t be used at the same time in Assign element..
        /// </summary>
        internal static string ErrorMessage_Source_and_Body_can_t_be_used_at_the_same_time_in_Assign_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Source_and_Body_can_t_be_used_at_the_same_time_in_Assign_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and SourceExpression can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_Source_and_SourceExpression_can_t_be_used_at_the_same_time_in_Invoke_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Source_and_SourceExpression_can_t_be_used_at_the_same_time_in_Invoke" +
                        "_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target and TargetExpression can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_Target_and_TargetExpression_can_t_be_used_at_the_same_time_in_Send_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Target_and_TargetExpression_can_t_be_used_at_the_same_time_in_Send_e" +
                        "lement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Id does not exists..
        /// </summary>
        internal static string ErrorMessage_Target_Id_does_not_exists {
            get {
                return ResourceManager.GetString("ErrorMessage_Target_Id_does_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition must be present in History element..
        /// </summary>
        internal static string ErrorMessage_Transition_must_be_present_in_History_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Transition_must_be_present_in_History_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition must be present in Initial element..
        /// </summary>
        internal static string ErrorMessage_Transition_must_be_present_in_Initial_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Transition_must_be_present_in_Initial_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type and TypeExpression can&apos;t be used at the same time in Invoke element..
        /// </summary>
        internal static string ErrorMessage_Type_and_TypeExpression_can_t_be_used_at_the_same_time_in_Invoke_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Type_and_TypeExpression_can_t_be_used_at_the_same_time_in_Invoke_ele" +
                        "ment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type and TypeExpression can&apos;t be used at the same time in Send element..
        /// </summary>
        internal static string ErrorMessage_Type_and_TypeExpression_can_t_be_used_at_the_same_time_in_Send_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Type_and_TypeExpression_can_t_be_used_at_the_same_time_in_Send_eleme" +
                        "nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or TypeExpression must be specified in Invoke element..
        /// </summary>
        internal static string ErrorMessage_Type_or_TypeExpression_must_be_specified_in_Invoke_element {
            get {
                return ResourceManager.GetString("ErrorMessage_Type_or_TypeExpression_must_be_specified_in_Invoke_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [url] has invalid URI format..
        /// </summary>
        internal static string ErrorMessage_url__has_invalid_URI_format {
            get {
                return ResourceManager.GetString("ErrorMessage_url__has_invalid_URI_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [url] and [urlExpr] attributes should not be assigned in Start element..
        /// </summary>
        internal static string ErrorMessage_url_and_urlExpr_attributes_should_not_be_assigned_in_Start_element {
            get {
                return ResourceManager.GetString("ErrorMessage_url_and_urlExpr_attributes_should_not_be_assigned_in_Start_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Value expression&apos; does not implement IValueEvaluator..
        /// </summary>
        internal static string ErrorMessage_Value_expression__does_not_implement_IValueEvaluator_ {
            get {
                return ResourceManager.GetString("ErrorMessage_Value_expression__does_not_implement_IValueEvaluator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml cannot be null..
        /// </summary>
        internal static string ErrorMessage_XmlCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_XmlCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access can&apos;t be changed..
        /// </summary>
        internal static string Exception_Access_can_t_be_changed {
            get {
                return ResourceManager.GetString("Exception_Access_can_t_be_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another asynchronous operation in progress..
        /// </summary>
        internal static string Exception_Another_asynchronous_operation_in_progress {
            get {
                return ResourceManager.GetString("Exception_Another_asynchronous_operation_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be DataModelDateTime type..
        /// </summary>
        internal static string Exception_Argument_must_be_DataModelDateTime_type {
            get {
                return ResourceManager.GetString("Exception_Argument_must_be_DataModelDateTime_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion failed..
        /// </summary>
        internal static string Exception_AssertionFailed {
            get {
                return ResourceManager.GetString("Exception_AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read raw content due to registered elements..
        /// </summary>
        internal static string Exception_Can_not_read_raw_content_due_to_registered_elements {
            get {
                return ResourceManager.GetString("Exception_Can_not_read_raw_content_due_to_registered_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not register component due to registered raw content..
        /// </summary>
        internal static string Exception_Can_not_register_component_due_to_registered_raw_content {
            get {
                return ResourceManager.GetString("Exception_Can_not_register_component_due_to_registered_raw_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not register raw content more than one time..
        /// </summary>
        internal static string Exception_Can_not_register_raw_content_more_than_one_time {
            get {
                return ResourceManager.GetString("Exception_Can_not_register_raw_content_more_than_one_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get access to IHost interface..
        /// </summary>
        internal static string Exception_Can_t_get_access_to_IHost_interface {
            get {
                return ResourceManager.GetString("Exception_Can_t_get_access_to_IHost_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t restore element..
        /// </summary>
        internal static string Exception_Can_t_restore_element {
            get {
                return ResourceManager.GetString("Exception_Can_t_restore_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find ResourceLoader to load external resource..
        /// </summary>
        internal static string Exception_Cannot_find_ResourceLoader_to_load_external_resource {
            get {
                return ResourceManager.GetString("Exception_Cannot_find_ResourceLoader_to_load_external_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find target..
        /// </summary>
        internal static string Exception_Cannot_find_target {
            get {
                return ResourceManager.GetString("Exception_Cannot_find_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find DataModelHandlerFactory for DataModel type &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_Cant_find_DataModelHandlerFactory_for_DataModel_type {
            get {
                return ResourceManager.GetString("Exception_Cant_find_DataModelHandlerFactory_for_DataModel_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel can&apos;t consume previously persisted object..
        /// </summary>
        internal static string Exception_Channel_can_t_consume_previously_persisted_object {
            get {
                return ResourceManager.GetString("Exception_Channel_can_t_consume_previously_persisted_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition does not specified..
        /// </summary>
        internal static string Exception_ConditionDoesNotSpecified {
            get {
                return ResourceManager.GetString("Exception_ConditionDoesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom action does not supported..
        /// </summary>
        internal static string Exception_CustomActionDoesNotSupported {
            get {
                return ResourceManager.GetString("Exception_CustomActionDoesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not Boolean..
        /// </summary>
        internal static string Exception_DataModelValue_is_not_Boolean {
            get {
                return ResourceManager.GetString("Exception_DataModelValue_is_not_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not DataModelList..
        /// </summary>
        internal static string Exception_DataModelValue_is_not_DataModelList {
            get {
                return ResourceManager.GetString("Exception_DataModelValue_is_not_DataModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not DateTime..
        /// </summary>
        internal static string Exception_DataModelValue_is_not_DateTime {
            get {
                return ResourceManager.GetString("Exception_DataModelValue_is_not_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not Number..
        /// </summary>
        internal static string Exception_DataModelValue_is_not_Number {
            get {
                return ResourceManager.GetString("Exception_DataModelValue_is_not_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModelValue is not String..
        /// </summary>
        internal static string Exception_DataModelValue_is_not_String {
            get {
                return ResourceManager.GetString("Exception_DataModelValue_is_not_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay parsing error. Format is ###0(ms|s)..
        /// </summary>
        internal static string Exception_DelayParsingError {
            get {
                return ResourceManager.GetString("Exception_DelayParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination list is not long enough to copy all the items in the collection. Check list index and length..
        /// </summary>
        internal static string Exception_Destination_array_is_not_long_enough {
            get {
                return ResourceManager.GetString("Exception_Destination_array_is_not_long_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on event consumer side. Exception message: {0}.
        ///{1}.
        /// </summary>
        internal static string Exception_Error_on_event_consumer_side {
            get {
                return ResourceManager.GetString("Exception_Error_on_event_consumer_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on parsing XPath expression..
        /// </summary>
        internal static string Exception_Error_on_parsing_XPath_expression {
            get {
                return ResourceManager.GetString("Exception_Error_on_parsing_XPath_expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event dispatcher not found..
        /// </summary>
        internal static string Exception_Event_dispatcher_not_found {
            get {
                return ResourceManager.GetString("Exception_Event_dispatcher_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Target did not specified..
        /// </summary>
        internal static string Exception_Event_Target_did_not_specified {
            get {
                return ResourceManager.GetString("Exception_Event_Target_did_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External communication does not configured for state machine interpreter..
        /// </summary>
        internal static string Exception_External_communication_does_not_configured_for_state_machine_interpreter {
            get {
                return ResourceManager.GetString("Exception_External_communication_does_not_configured_for_state_machine_interprete" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward entities required to restore state machine..
        /// </summary>
        internal static string Exception_Forward_entities_required_to_restore_state_machine {
            get {
                return ResourceManager.GetString("Exception_Forward_entities_required_to_restore_state_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward entity can not be found..
        /// </summary>
        internal static string Exception_Forward_entity_can_not_be_found {
            get {
                return ResourceManager.GetString("Exception_Forward_entity_can_not_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward entity has incorrect type..
        /// </summary>
        internal static string Exception_Forward_entity_has_incorrect_type {
            get {
                return ResourceManager.GetString("Exception_Forward_entity_has_incorrect_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier cannot contains whitespace..
        /// </summary>
        internal static string Exception_IdentifierCannotContainsWhitespace {
            get {
                return ResourceManager.GetString("Exception_IdentifierCannotContainsWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data format..
        /// </summary>
        internal static string Exception_Incorrect_data_format {
            get {
                return ResourceManager.GetString("Exception_Incorrect_data_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect encoding..
        /// </summary>
        internal static string Exception_Incorrect_encoding {
            get {
                return ResourceManager.GetString("Exception_Incorrect_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index should be non-negative and less then array size..
        /// </summary>
        internal static string Exception_Index_should_be_non_negative_and_less_then_aarray_size {
            get {
                return ResourceManager.GetString("Exception_Index_should_be_non_negative_and_less_then_aarray_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index value must be non-negative integer..
        /// </summary>
        internal static string Exception_Index_value_must_be_non_negative_integer {
            get {
                return ResourceManager.GetString("Exception_Index_value_must_be_non_negative_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIncludeReader does not support in-document references..
        /// </summary>
        internal static string Exception_IndocumentReferencesNotSupported {
            get {
                return ResourceManager.GetString("Exception_IndocumentReferencesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal events can&apos;t be delayed..
        /// </summary>
        internal static string Exception_Internal_events_can_t_be_delayed {
            get {
                return ResourceManager.GetString("Exception_Internal_events_can_t_be_delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal events can&apos;t be delayed..
        /// </summary>
        internal static string Exception_Internal_events_can_t_be_delayed_ {
            get {
                return ResourceManager.GetString("Exception_Internal_events_can_t_be_delayed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InvokeId..
        /// </summary>
        internal static string Exception_Invalid_InvokeId {
            get {
                return ResourceManager.GetString("Exception_Invalid_InvokeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type..
        /// </summary>
        internal static string Exception_Invalid_type {
            get {
                return ResourceManager.GetString("Exception_Invalid_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TypeInfo value..
        /// </summary>
        internal static string Exception_Invalid_TypeInfo_value {
            get {
                return ResourceManager.GetString("Exception_Invalid_TypeInfo_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_InvalidURI {
            get {
                return ResourceManager.GetString("Exception_InvalidURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed InvokeId..
        /// </summary>
        internal static string Exception_InvokedServiceMeta_Missed_InvokeId {
            get {
                return ResourceManager.GetString("Exception_InvokedServiceMeta_Missed_InvokeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Processor has not been started..
        /// </summary>
        internal static string Exception_IO_Processor_has_not_been_started {
            get {
                return ResourceManager.GetString("Exception_IO_Processor_has_not_been_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item can&apos;t be null..
        /// </summary>
        internal static string Exception_Item_can_t_be_null {
            get {
                return ResourceManager.GetString("Exception_Item_can_t_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; key not found..
        /// </summary>
        internal static string Exception_key_not_found {
            get {
                return ResourceManager.GetString("Exception_key_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of events cannot be empty..
        /// </summary>
        internal static string Exception_ListOfEventsCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ListOfEventsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of identifiers cannot be empty..
        /// </summary>
        internal static string Exception_ListOfIdentifiersCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ListOfIdentifiersCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of locations cannot be empty..
        /// </summary>
        internal static string Exception_ListOfLocationsCannotBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ListOfLocationsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading external resources does not supported. Derive class from ScxmlXmlResolver and pass instance of it to ScxmlDirector..
        /// </summary>
        internal static string Exception_Loading_external_resources_does_not_supported {
            get {
                return ResourceManager.GetString("Exception_Loading_external_resources_does_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location does not specified..
        /// </summary>
        internal static string Exception_LocationDoesNotSpecified {
            get {
                return ResourceManager.GetString("Exception_LocationDoesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed ParentSessionId..
        /// </summary>
        internal static string Exception_Missed_ParentSessionId {
            get {
                return ResourceManager.GetString("Exception_Missed_ParentSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed SessionId..
        /// </summary>
        internal static string Exception_Missed_SessionId {
            get {
                return ResourceManager.GetString("Exception_Missed_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedIoProcessor with name &apos;{0}&apos; already has been registered..
        /// </summary>
        internal static string Exception_NamedIoProcessor_with_name_already_has_been_registered {
            get {
                return ResourceManager.GetString("Exception_NamedIoProcessor_with_name_already_has_been_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting level reached, probably circular inclusion..
        /// </summary>
        internal static string Exception_NestingReachedLevelInclusion {
            get {
                return ResourceManager.GetString("Exception_NestingReachedLevelInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object can not be modified..
        /// </summary>
        internal static string Exception_Object_can_not_be_modified {
            get {
                return ResourceManager.GetString("Exception_Object_can_not_be_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition argument should be null..
        /// </summary>
        internal static string Exception_Partition_argument_should_be_null {
            get {
                return ResourceManager.GetString("Exception_Partition_argument_should_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persisted state can&apos;t be read. Stored and provided SessionIds does not match..
        /// </summary>
        internal static string Exception_Persisted_state_can_t_be_read__Stored_and_provided_SessionIds_does_not_match {
            get {
                return ResourceManager.GetString("Exception_Persisted_state_can_t_be_read__Stored_and_provided_SessionIds_does_not_" +
                        "match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persisted state can&apos;t be read. Unsupported version..
        /// </summary>
        internal static string Exception_Persisted_state_can_t_be_read__Unsupported_version_ {
            get {
                return ResourceManager.GetString("Exception_Persisted_state_can_t_be_read__Unsupported_version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix {0} can&apos;t be resolved..
        /// </summary>
        internal static string Exception_Prefix_cant_be_resolved {
            get {
                return ResourceManager.GetString("Exception_Prefix_cant_be_resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration should no occur after initialization..
        /// </summary>
        internal static string Exception_Registration_should_no_occur_after_initialization {
            get {
                return ResourceManager.GetString("Exception_Registration_should_no_occur_after_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; not found..
        /// </summary>
        internal static string Exception_Resource_not_found {
            get {
                return ResourceManager.GetString("Exception_Resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of XPath expression can&apos;t be identified..
        /// </summary>
        internal static string Exception_Result_of_XPath_expression_can_t_be_identified {
            get {
                return ResourceManager.GetString("Exception_Result_of_XPath_expression_can_t_be_identified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of XPath expression should be boolean value..
        /// </summary>
        internal static string Exception_Result_of_XPath_expression_should_be_boolean_value {
            get {
                return ResourceManager.GetString("Exception_Result_of_XPath_expression_should_be_boolean_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of XPath expression should be element..
        /// </summary>
        internal static string Exception_Result_of_XPath_expression_should_be_element {
            get {
                return ResourceManager.GetString("Exception_Result_of_XPath_expression_should_be_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path can be set only before visiting..
        /// </summary>
        internal static string Exception_Root_path_can_be_set_only_before_visiting {
            get {
                return ResourceManager.GetString("Exception_Root_path_can_be_set_only_before_visiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendId is empty..
        /// </summary>
        internal static string Exception_SendIdIsEmpty {
            get {
                return ResourceManager.GetString("Exception_SendIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId could not be empty..
        /// </summary>
        internal static string Exception_SessionId_could_not_be_empty {
            get {
                return ResourceManager.GetString("Exception_SessionId_could_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified method is not supported in type {0}..
        /// </summary>
        internal static string Exception_Specified_method_is_not_supported_in_type {
            get {
                return ResourceManager.GetString("Exception_Specified_method_is_not_supported_in_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine external queue has been closed..
        /// </summary>
        internal static string Exception_State_Machine_external_queue_has_been_closed {
            get {
                return ResourceManager.GetString("Exception_State_Machine_external_queue_has_been_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine has been destroyed..
        /// </summary>
        internal static string Exception_State_Machine_has_been_destroyed {
            get {
                return ResourceManager.GetString("Exception_State_Machine_has_been_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine has been halted..
        /// </summary>
        internal static string Exception_State_Machine_has_been_halted {
            get {
                return ResourceManager.GetString("Exception_State_Machine_has_been_halted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine has been suspended..
        /// </summary>
        internal static string Exception_State_Machine_has_been_suspended {
            get {
                return ResourceManager.GetString("Exception_State_Machine_has_been_suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateId not initialized..
        /// </summary>
        internal static string Exception_StateId_not_initialized {
            get {
                return ResourceManager.GetString("Exception_StateId_not_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachine origin missed..
        /// </summary>
        internal static string Exception_StateMachine_origin_missed {
            get {
                return ResourceManager.GetString("Exception_StateMachine_origin_missed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateMachineHost stopped..
        /// </summary>
        internal static string Exception_StateMachineHost_stopped {
            get {
                return ResourceManager.GetString("Exception_StateMachineHost_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message #{0} of {1}: {2}.
        /// </summary>
        internal static string Exception_StateMachineValidationException_Message {
            get {
                return ResourceManager.GetString("Exception_StateMachineValidationException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage not available for read operations.
        /// </summary>
        internal static string Exception_Storage_not_available_for_read_operations {
            get {
                return ResourceManager.GetString("Exception_Storage_not_available_for_read_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream should support Read, Write, Seek operations..
        /// </summary>
        internal static string Exception_StreamShouldSupportReadWriteSeekOperations {
            get {
                return ResourceManager.GetString("Exception_StreamShouldSupportReadWriteSeekOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target should be equal to &apos;_parent&apos; or null..
        /// </summary>
        internal static string Exception_Target_should_be_equal_to___parent__or_null {
            get {
                return ResourceManager.GetString("Exception_Target_should_be_equal_to___parent__or_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target wrong format..
        /// </summary>
        internal static string Exception_Target_wrong_format {
            get {
                return ResourceManager.GetString("Exception_Target_wrong_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type, SendId, DelayMs can&apos;t be specified for this event..
        /// </summary>
        internal static string Exception_Type__SendId__DelayMs_can_t_be_specified_for_this_event {
            get {
                return ResourceManager.GetString("Exception_Type__SendId__DelayMs_can_t_be_specified_for_this_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can&apos;t be found in type &apos;{1}&apos; or in its ancestors..
        /// </summary>
        internal static string Exception_TypeCantBeFound {
            get {
                return ResourceManager.GetString("Exception_TypeCantBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type attribute value: {0}..
        /// </summary>
        internal static string Exception_Unexpected_type_attribute_value {
            get {
                return ResourceManager.GetString("Exception_Unexpected_type_attribute_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected TypeInfo value.
        ///.
        /// </summary>
        internal static string Exception_Unexpected_TypeInfo_value {
            get {
                return ResourceManager.GetString("Exception_Unexpected_TypeInfo_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value..
        /// </summary>
        internal static string Exception_UnexpectedValue {
            get {
                return ResourceManager.GetString("Exception_UnexpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception..
        /// </summary>
        internal static string Exception_Unhandled_exception {
            get {
                return ResourceManager.GetString("Exception_Unhandled_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Condition type..
        /// </summary>
        internal static string Exception_Unknown_Condition_type {
            get {
                return ResourceManager.GetString("Exception_Unknown_Condition_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Executable Entity type..
        /// </summary>
        internal static string Exception_Unknown_Executable_Entity_type {
            get {
                return ResourceManager.GetString("Exception_Unknown_Executable_Entity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown State Entity type..
        /// </summary>
        internal static string Exception_Unknown_State_Entity_type {
            get {
                return ResourceManager.GetString("Exception_Unknown_State_Entity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown XPath function. Namespace:&apos;{0}&apos;, Name:&apos;{1}&apos;..
        /// </summary>
        internal static string Exception_Unknown_XPath_function {
            get {
                return ResourceManager.GetString("Exception_Unknown_XPath_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown XPath variable. Namespace:&apos;{0}&apos;, Name:&apos;{1}&apos;..
        /// </summary>
        internal static string Exception_Unknown_XPath_variable {
            get {
                return ResourceManager.GetString("Exception_Unknown_XPath_variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown &apos;parse&apos; attribute value: &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_UnknownParseAttrValue {
            get {
                return ResourceManager.GetString("Exception_UnknownParseAttrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve URI reference &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_UnresolvableURI {
            get {
                return ResourceManager.GetString("Exception_UnresolvableURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported object type..
        /// </summary>
        internal static string Exception_Unsupported_object_type {
            get {
                return ResourceManager.GetString("Exception_Unsupported_object_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedirectXmlResolver not supported class: {0}..
        /// </summary>
        internal static string Exception_UnsupportedClass {
            get {
                return ResourceManager.GetString("Exception_UnsupportedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SCXML version..
        /// </summary>
        internal static string Exception_UnsupportedScxmlVersion {
            get {
                return ResourceManager.GetString("Exception_UnsupportedScxmlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported {0} type: [{1}]..
        /// </summary>
        internal static string Exception_UnsupportedType {
            get {
                return ResourceManager.GetString("Exception_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ReadAsync() instead..
        /// </summary>
        internal static string Exception_Use_ReadAsync___instead {
            get {
                return ResourceManager.GetString("Exception_Use_ReadAsync___instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use WriteAsync() instead..
        /// </summary>
        internal static string Exception_Use_WriteAsync___instead {
            get {
                return ResourceManager.GetString("Exception_Use_WriteAsync___instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression must be present..
        /// </summary>
        internal static string Exception_Value_Expression_must_be_present {
            get {
                return ResourceManager.GetString("Exception_Value_Expression_must_be_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not SCXML..
        /// </summary>
        internal static string Exception_Value_is_not_SCXML {
            get {
                return ResourceManager.GetString("Exception_Value_is_not_SCXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not Source..
        /// </summary>
        internal static string Exception_Value_is_not_Source {
            get {
                return ResourceManager.GetString("Exception_Value_is_not_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not StateMachine..
        /// </summary>
        internal static string Exception_Value_is_not_StateMachine {
            get {
                return ResourceManager.GetString("Exception_Value_is_not_StateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be non negative integer..
        /// </summary>
        internal static string Exception_Value_must_be_non_negative_integer {
            get {
                return ResourceManager.GetString("Exception_Value_must_be_non_negative_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be an empty collection..
        /// </summary>
        internal static string Exception_ValueCannotBeAnEmptyCollection {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeAnEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be an empty list..
        /// </summary>
        internal static string Exception_ValueCannotBeAnEmptyList {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeAnEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty list..
        /// </summary>
        internal static string Exception_ValueCannotBeEmptyList {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string Exception_ValueCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be parsed for type {0}..
        /// </summary>
        internal static string Exception_ValueCannotBeParsed {
            get {
                return ResourceManager.GetString("Exception_ValueCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be empty..
        /// </summary>
        internal static string Exception_ValueCantBeEmpty {
            get {
                return ResourceManager.GetString("Exception_ValueCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Line {1}, Position {2}..
        /// </summary>
        internal static string Exception_XIncludeException_Line_Position {
            get {
                return ResourceManager.GetString("Exception_XIncludeException_Line_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Location: {1}..
        /// </summary>
        internal static string Exception_XIncludeException_Location {
            get {
                return ResourceManager.GetString("Exception_XIncludeException_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Location: {1}, Line {2}, Position {3}..
        /// </summary>
        internal static string Exception_XIncludeException_Location_Line_Position {
            get {
                return ResourceManager.GetString("Exception_XIncludeException_Location_Line_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occurred during GetEntity call to XmlResolver..
        /// </summary>
        internal static string Exception_XmlResolverGetEntity {
            get {
                return ResourceManager.GetString("Exception_XmlResolverGetEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlResolver returned null..
        /// </summary>
        internal static string Exception_XmlResolverReturnedNull {
            get {
                return ResourceManager.GetString("Exception_XmlResolverReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message read partially. {0} of {1} bytes..
        /// </summary>
        internal static string NamedIoProcessor_Message_read_partially {
            get {
                return ResourceManager.GetString("NamedIoProcessor_Message_read_partially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message size has wrong value or missed. Size: {0} bytes..
        /// </summary>
        internal static string NamedIoProcessor_Message_size_has_wrong_value_or_missed {
            get {
                return ResourceManager.GetString("NamedIoProcessor_Message_size_has_wrong_value_or_missed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source not specified..
        /// </summary>
        internal static string StartAction_Execute_Source_not_specified {
            get {
                return ResourceManager.GetString("StartAction_Execute_Source_not_specified", resourceCulture);
            }
        }
    }
}
