//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtate.IoC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtate.IoC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion failed..
        /// </summary>
        internal static string Exception_AssertionFailed {
            get {
                return ResourceManager.GetString("Exception_AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1})..
        /// </summary>
        internal static string Exception_AssertUnexpected {
            get {
                return ResourceManager.GetString("Exception_AssertUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}:{2})..
        /// </summary>
        internal static string Exception_AssertUnexpectedWithType {
            get {
                return ResourceManager.GetString("Exception_AssertUnexpectedWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t cast/forward delegate {0} to {1}..
        /// </summary>
        internal static string Exception_CantCastForwardDelegate {
            get {
                return ResourceManager.GetString("Exception_CantCastForwardDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find factory for type [{0}]..
        /// </summary>
        internal static string Exception_CantFindFactoryForType {
            get {
                return ResourceManager.GetString("Exception_CantFindFactoryForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t match arguments for implementation class..
        /// </summary>
        internal static string Exception_CantMatchArgumentsForImplementationClass {
            get {
                return ResourceManager.GetString("Exception_CantMatchArgumentsForImplementationClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate creation failed..
        /// </summary>
        internal static string Exception_DelegateCreationFailed {
            get {
                return ResourceManager.GetString("Exception_DelegateCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory of [{0}] raised exception..
        /// </summary>
        internal static string Exception_FactoryOfRaisedException {
            get {
                return ResourceManager.GetString("Exception_FactoryOfRaisedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type..
        /// </summary>
        internal static string Exception_InvalidType {
            get {
                return ResourceManager.GetString("Exception_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one constructor found..
        /// </summary>
        internal static string Exception_MoreThanOneConstructorFound {
            get {
                return ResourceManager.GetString("Exception_MoreThanOneConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one method found..
        /// </summary>
        internal static string Exception_MoreThanOneMethodFound {
            get {
                return ResourceManager.GetString("Exception_MoreThanOneMethodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructor found..
        /// </summary>
        internal static string Exception_NoConstructorFound {
            get {
                return ResourceManager.GetString("Exception_NoConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method found..
        /// </summary>
        internal static string Exception_NoMethodFound {
            get {
                return ResourceManager.GetString("Exception_NoMethodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider creation failed..
        /// </summary>
        internal static string Exception_ProviderCreationFailed {
            get {
                return ResourceManager.GetString("Exception_ProviderCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service [{0} (Argument: {1})] missed in container..
        /// </summary>
        internal static string Exception_ServiceArgMissedInContainer {
            get {
                return ResourceManager.GetString("Exception_ServiceArgMissedInContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service can&apos;t be instantiated since at least one parameter required asynchronous call..
        /// </summary>
        internal static string Exception_ServiceCantBeInstantiatedSinceAtLeastOneParameterRequiredAsynchronousCall {
            get {
                return ResourceManager.GetString("Exception_ServiceCantBeInstantiatedSinceAtLeastOneParameterRequiredAsynchronousCa" +
                        "ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service [{0}] missed in container..
        /// </summary>
        internal static string Exception_ServiceMissedInContainer {
            get {
                return ResourceManager.GetString("Exception_ServiceMissedInContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service [{0}] not available in synchronous context..
        /// </summary>
        internal static string Exception_ServiceNotAvailableInSynchronousContext {
            get {
                return ResourceManager.GetString("Exception_ServiceNotAvailableInSynchronousContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceType not initialized..
        /// </summary>
        internal static string Exception_ServiceTypeNotInitialized {
            get {
                return ResourceManager.GetString("Exception_ServiceTypeNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton/scoped types does not supported for synchronous instantiation..
        /// </summary>
        internal static string Exception_SingletonScopedTypesDoesNotSupportedForSynchronousInstantiation {
            get {
                return ResourceManager.GetString("Exception_SingletonScopedTypesDoesNotSupportedForSynchronousInstantiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exception should never happen..
        /// </summary>
        internal static string Exception_ThisExceptionShouldNeverHappen {
            get {
                return ResourceManager.GetString("Exception_ThisExceptionShouldNeverHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} can&apos;t be cast to {1}..
        /// </summary>
        internal static string Exception_TypeCantBeCastedTo {
            get {
                return ResourceManager.GetString("Exception_TypeCantBeCastedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} can&apos;t be constructed based on service type {1}..
        /// </summary>
        internal static string Exception_TypeCantBeConstructedBasedOnServiceType {
            get {
                return ResourceManager.GetString("Exception_TypeCantBeConstructedBasedOnServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not contains method (or ambiguity) with return type: (ValueTask&lt;{1}&gt; or {1}) and empty or single CancellationToken input parameter..
        /// </summary>
        internal static string Exception_TypeDoesNotContainsMethodWithSignatureMethodCancellationToken {
            get {
                return ResourceManager.GetString("Exception_TypeDoesNotContainsMethodWithSignatureMethodCancellationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} used in synchronous instantiation and can&apos;t be initialized asynchronously..
        /// </summary>
        internal static string Exception_TypeUsedInSynchronousInstantiation {
            get {
                return ResourceManager.GetString("Exception_TypeUsedInSynchronousInstantiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value..
        /// </summary>
        internal static string Exception_UnexpectedValue {
            get {
                return ResourceManager.GetString("Exception_UnexpectedValue", resourceCulture);
            }
        }
    }
}
