//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtate.EcmaScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtate.DataModel.EcmaScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Expression must be present..
        /// </summary>
        internal static string ErrorMessage_Condition_Expression_must_be_present {
            get {
                return ResourceManager.GetString("ErrorMessage_Condition_Expression_must_be_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement must be a single assignable variable or object property..
        /// </summary>
        internal static string ErrorMessage_InvalidLocationExpression {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidLocationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Expression must be present..
        /// </summary>
        internal static string ErrorMessage_Location_Expression_must_be_present {
            get {
                return ResourceManager.GetString("ErrorMessage_Location_Expression_must_be_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Expression must be present..
        /// </summary>
        internal static string ErrorMessage_Script_Expression_must_be_present {
            get {
                return ResourceManager.GetString("ErrorMessage_Script_Expression_must_be_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression must be present..
        /// </summary>
        internal static string ErrorMessage_Value_Expression_must_be_present {
            get {
                return ResourceManager.GetString("ErrorMessage_Value_Expression_must_be_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External script missed..
        /// </summary>
        internal static string Exception_ExternalScriptMissed {
            get {
                return ResourceManager.GetString("Exception_ExternalScriptMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid variable name..
        /// </summary>
        internal static string Exception_InvalidLocalVariableName {
            get {
                return ResourceManager.GetString("Exception_InvalidLocalVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Location Expression can&apos;t be evaluated..
        /// </summary>
        internal static string Exception_Name_of_Location_Expression_can_t_be_evaluated {
            get {
                return ResourceManager.GetString("Exception_Name_of_Location_Expression_can_t_be_evaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value of value.Type parameter..
        /// </summary>
        internal static string Exception_UnsupportedValueType {
            get {
                return ResourceManager.GetString("Exception_UnsupportedValueType", resourceCulture);
            }
        }
    }
}
